---
- name:  cv_device_v3 lab
  hosts: cv_server
  connection: local
  gather_facts: no

  tasks:
    - name: "Push config to {{inventory_hostname}}"
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: present
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        search_key: 'fqdn'
        state: present
      register: CVP_DEVICES_RESULTS

