static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.255.0.254
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - 10.255.0.1:9910
  cvauth:
    method: key
    key: ''
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 17.1.1.10
  - 8.8.8.8
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$HEB.p1pQpAMXnkAJ$UP03UskWJlBKYcu62NrvIpVrjrB37Q3REuMFNzqxmkGus5pQIqcZA0dqNMHXDzFy2oZQa2jHZPqBmULxFsVcG.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$yHKaDAJreUKUh.Am$w2EeKoYPKgRdxOdkNcXLRlv6sdWPc6/yb1Ct/hMTdNwoygwEjpqzks5RAiTRWy5SoRZxJR1UbdncJGR2hXwhI0
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$CWrVRj8kyDRwfBAd$yBfrAoX.CwKxsldub1GDVqwVEB3hhrOXCafHoSq1OZcMpzzQR/3/3t408RqPtywmr8ttCI04eymCCOPNS.CtI/
  test1:
    privilege: 15
    role: network-admin
    sha512_password: $6$yHKaDAJreUKUh.Am$w2EeKoYPKgRdxOdkNcXLRlv6sdWPc6/yb1Ct/hMTdNwoygwEjpqzks5RAiTRWy5SoRZxJR1UbdncJGR2hXwhI0
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.255.0.18/24
    gateway: 10.255.0.254
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: DC1-LEAF2A
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF2A_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: DC1-LEAF2B
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF2B_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet3:
    peer: server02
    peer_interface: Eth0
    peer_type: server
    description: server02_Eth0
    type: switched
    shutdown: false
    mode: trunk
    vlans: 110-111,210-211
  Ethernet4:
    peer: server04
    peer_interface: Eth0
    peer_type: server
    description: server04_Eth0
    type: switched
    shutdown: false
    mode: trunk
    vlans: 110-111,210-211
port_channel_interfaces:
  Port-Channel1:
    description: DC1_LEAF2_Po5
    type: switched
    shutdown: false
    vlans: 110-112,120-121,130-131
    mode: trunk
vlans:
  130:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_1
  131:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_2
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  120:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone_1
  121:
    tenant: Tenant_A
    name: Tenant_A_WEBZone_2
ip_igmp_snooping:
  globally_enabled: true
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.sg.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.sg.pool.ntp.org
    vrf: MGMT
