---
- name:  cv_container_v3 lab
  hosts: cv_server
  connection: local
  gather_facts: no
  tasks:
    - name: "Configure containers on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS}}"
        state: present
      register: CVP_CONTAINERS_RESULT
    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{DEVICES}}"
        apply_mode: loose
        state: present
    - name: "Display cv_configlet result"
      debug:
        msg: "{{CVP_CONTAINERS_RESULT}}"
