---
- name: lab03 - cv_facts lab
  hosts: cv_server
  connection: local
  gather_facts: no
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cv_facts

    - name: "Print out facts from {{inventory_hostname}}"
      debug:
        msg: "{{cv_facts}}"
