---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$HEB.p1pQpAMXnkAJ$UP03UskWJlBKYcu62NrvIpVrjrB37Q3REuMFNzqxmkGus5pQIqcZA0dqNMHXDzFy2oZQa2jHZPqBmULxFsVcG."

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$CWrVRj8kyDRwfBAd$yBfrAoX.CwKxsldub1GDVqwVEB3hhrOXCafHoSq1OZcMpzzQR/3/3t408RqPtywmr8ttCI04eymCCOPNS.CtI/"

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$yHKaDAJreUKUh.Am$w2EeKoYPKgRdxOdkNcXLRlv6sdWPc6/yb1Ct/hMTdNwoygwEjpqzks5RAiTRWy5SoRZxJR1UbdncJGR2hXwhI0"
  test1:
    privilege: 15
    role: network-admin
    sha512_password: "$6$yHKaDAJreUKUh.Am$w2EeKoYPKgRdxOdkNcXLRlv6sdWPc6/yb1Ct/hMTdNwoygwEjpqzks5RAiTRWy5SoRZxJR1UbdncJGR2hXwhI0"

# Cloud Vision server information
cvp_instance_ip: 10.255.0.1
cvp_ingestauth_key: ''
# cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 10.255.0.254

# dns servers.
name_servers:
  - 17.1.1.10
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
custom_structured_configuration_ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.sg.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.sg.pool.ntp.org
    vrf: MGMT
