---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"
  TENANT_A:
    mode: access
    vlans: "110"
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet3]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A_B
  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet3]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A_B
  server03:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet4]
        switches: [DC1-L2LEAF1A]
        profile: TENANT_A_B
  server04:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet4]
        switches: [DC1-L2LEAF2A]
        profile: TENANT_A_B
